import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { QueryClient, dehydrate, useQuery } from 'react-query';
import apiClient from '@/lib/apiClient';

const inter = Inter({ subsets: ['latin'] });

const getTrending = async () => {
  const client = apiClient();
  try {
    const movies = await client.get('/trending/movie/day');
    const tv = await client.get('/trending/tv/day');
    return {
      movies: movies.data.results,
      tv: tv.data.results,
    };
  } catch (e) {
    console.log(e);
  }
};

export default function Home(props: { trending: any }) {
  const { data, isLoading } = useQuery('trending', getTrending, {
    initialData: props.trending,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <div className="min-h-[700px] w-full bg-indigo-800 relative">
          <div className="absolute top-0 right-0 left-0 bottom-0 flex flex-col items-center justify-center h-full">
            <Image
              alt="hero"
              src={
                'https://image.tmdb.org/t/p/original' +
                data.movies[0].backdrop_path
              }
              fill
            />
          </div>
          <div className="flex flex-col items-center justify-center h-full"></div>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const trending = await getTrending();
  return { props: { trending: trending } };
}
